apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-api-deployment
spec:
  replicas: 5
  selector:
    matchLabels:
      app: auth-api
  template:
    metadata:
      labels:
        app: auth-api
    spec:
      containers:
      - name: auth-1
        image: nancylence/project-auth:latest
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 80
