apiVersion: apps/v1
kind: Deployment
metadata:
  name: users-api-deployment
spec:
  selector:
    matchLabels:
      app: users-api
  template:
    metadata:
      labels:
        app: users-api
    spec:
      containers:
      - name: users-1
        image: nancylence/project-users:latest
        env:
          - name: AUTH_ADDRESS
            valueFrom:
              configMapKeyRef:
                name: exokub-final-env
                key: AUTH_ADDRESS
        resources:
          limits:
            memory: "512Mi"
            cpu: "500m"
        ports:
        - containerPort: 8080